#ifndef __MainFrame__
#define __MainFrame__

/**
@file
Subclass of MainFrame_Base, which is generated by wxFormBuilder.
*/

#include "RayoffailGUI.h"

#include "../Scene.h"
#include "../Camera.h"
#include "../Renderer.h"


/** Implementing MainFrame_Base */
class MainFrame : public MainFrame_Base
{
public:
	/** Constructor */
	MainFrame( wxWindow* parent );

	//Event handlers
	virtual void onIdle( wxIdleEvent& event );
	virtual void onStart( wxCommandEvent& event );
	virtual void onOpenMenu( wxCommandEvent& event );
	virtual void onSaveImageMenu( wxCommandEvent& event );
	virtual void onAboutMenu( wxCommandEvent& event );

private:
	Renderer *renderer;
	Scene *scene;
	Camera *camera;

	bool rendering;
	Image *img;
	wxImage *image;
	wxBitmap *bitmap;

	void refreshPreview();
};

#endif // __MainFrame__
