#ifndef __MainFrame__
#define __MainFrame__

/**
@file
Subclass of MainFrame_Base, which is generated by wxFormBuilder.
*/

#include "RayoffailGUI.h"

#include "../Scene.h"
#include "../Camera.h"
#include "../Renderer.h"


/** Implementing MainFrame_Base */
class MainFrame : public MainFrame_Base
{
public:
	/** Constructor */
	MainFrame( wxWindow* parent );

	//Event handlers
	virtual void onStart( wxCommandEvent& event );
	virtual void onOpenMenu( wxCommandEvent& event );
	virtual void onSaveImageMenu( wxCommandEvent& event );
	virtual void onAboutMenu( wxCommandEvent& event );

private:
	Renderer *renderer;

	Scene *scene;
	Camera *camera;
};

#endif // __MainFrame__
